kind: pipeline
name: kernel_realme_sdm710

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: spiral_kernel
    image: ubuntu:latest
    environment:
      CI_CHANNEL_ID:
        from_secret: ci_channel_id
      BOT_API_KEY:
        from_secret:
      RELEASE_VERSION:
    commands:
      - apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git zip python flex
      - git clone --depth=1 https://github.com/viciouspup/Drone-scripts.git script && cd script
      - bash setup-drone.sh --proton
      - bash build-kernel.sh --proton
pipeline:
  telegram-notification:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]
    format: markdown
    message: >
      {{#success build.status}}
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.


      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```


      🌐 {{ build.link }}
      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.


      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```


      🌐 {{ build.link }}
      {{/success}}
